site_name: TG template
site_url: https://nfdi.fiz-karlsruhe.de/kg-template/
repo_url: https://github.com/ebrahimnorouzi/KG-Template
nav:
  - Home: index.md
  - SPARQL Endpoint: /kg-template/shmarql/
  - Sample Queries:
    - Statistics: statistics.md
